In [1]:
import numpy as np

Crea un array con elementos del 20 al 60 inclusives

In [2]:
array = np.arange(20,61,1)
array

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
       54, 55, 56, 57, 58, 59, 60])

Crea un array de una dimension con 15 elementos de unos, luego cambiar el tercer elemento a 99

In [3]:
array = np.ones((1,15))
array

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [4]:
array[0,2]=99
array

array([[ 1.,  1., 99.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.]])

Crea una matriz de 6 * 6 de ceros

In [5]:
array = np.zeros((6,6))
array

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

Convertir el tipo de datos anterior a entero





In [6]:
array.dtype.name

'float64'

In [7]:
array.dtype="int64"
array.dtype.name

'int64'

In [8]:
array

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

Crea un array de numeros enteros del 1 al 20 inclusives, con 4 filas y 3 columnas, muestra el valor de la segunda fila y primera columna

In [9]:
array = np.random.randint(1,21,size=12)
array

array([ 7,  7, 14, 10, 11, 10,  4, 12,  3, 10, 17, 20], dtype=int32)

In [10]:
array = array.reshape(4,3)
array

array([[ 7,  7, 14],
       [10, 11, 10],
       [ 4, 12,  3],
       [10, 17, 20]], dtype=int32)

In [11]:
array[1,0]

np.int32(10)

Crea un array con valores del rango 50 a 99 inclusives

In [12]:
array=np.arange(50,100)
array

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66,
       67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83,
       84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

Invierte el array anterior

In [13]:
array[::-1]

array([99, 98, 97, 96, 95, 94, 93, 92, 91, 90, 89, 88, 87, 86, 85, 84, 83,
       82, 81, 80, 79, 78, 77, 76, 75, 74, 73, 72, 71, 70, 69, 68, 67, 66,
       65, 64, 63, 62, 61, 60, 59, 58, 57, 56, 55, 54, 53, 52, 51, 50])

Crea una matriz 4 * 4 con valores de 1 a 16

In [14]:
array = np.arange(1,17).reshape(4,4)
array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

Encontrar los valores mayores a 6 del array anterior

In [15]:
array_sup_6 = array[array>6]
array_sup_6

array([ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

Crear una matriz identidad de 5 * 5

In [16]:
array = np.identity(5)
array

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

Crear matriz con valores al azar entre 0 y 1 de forma 4x4x4

In [17]:
array = np.random.random((4,4,4))
array

array([[[0.50125571, 0.77511746, 0.56830517, 0.40275884],
        [0.44583911, 0.13075485, 0.01458722, 0.45102543],
        [0.26383385, 0.82829687, 0.62245806, 0.92114047],
        [0.14890305, 0.58108667, 0.98868672, 0.44142866]],

       [[0.24823565, 0.2583278 , 0.62666426, 0.48024455],
        [0.12596699, 0.00296409, 0.85937826, 0.67730759],
        [0.75671491, 0.6735798 , 0.51963057, 0.20462825],
        [0.11250016, 0.9663947 , 0.67672259, 0.57404672]],

       [[0.83053102, 0.64703562, 0.85495982, 0.2147047 ],
        [0.52430029, 0.52708472, 0.36902995, 0.64826413],
        [0.9691936 , 0.16398232, 0.47087712, 0.7430103 ],
        [0.96751262, 0.94598957, 0.54549391, 0.14297371]],

       [[0.9389996 , 0.49322177, 0.4913885 , 0.2868469 ],
        [0.83426698, 0.79662371, 0.79048767, 0.88640066],
        [0.13879713, 0.24694868, 0.72836698, 0.52111302],
        [0.11126813, 0.84457042, 0.3571695 , 0.37108406]]])

Indicar valor minimo y maximo del array anterior y su posicion


In [18]:
array.min()

np.float64(0.002964085612153333)

In [19]:
array.argmin()

np.int64(21)

In [20]:
array.max()

np.float64(0.9886867186459465)

In [21]:
array.argmax()

np.int64(14)

Crear 2 arrays al azar y verificar si son iguales

In [22]:
array_1 = np.random.random((5,5))
array_1

array([[0.25115134, 0.87881346, 0.35878896, 0.70915787, 0.28337425],
       [0.99631287, 0.0431614 , 0.75517756, 0.3201813 , 0.68393273],
       [0.6603961 , 0.45728438, 0.31255733, 0.39210108, 0.2065281 ],
       [0.82399602, 0.54326308, 0.53090704, 0.14128877, 0.56175075],
       [0.37244941, 0.25533817, 0.8767043 , 0.66638463, 0.71308245]])

In [23]:
array_2 = np.random.random((5,5))
array_2

array([[0.01825154, 0.6881296 , 0.19589701, 0.58892569, 0.97351639],
       [0.24463183, 0.95440369, 0.90828175, 0.27649801, 0.6842659 ],
       [0.01233237, 0.32496628, 0.58334339, 0.23594468, 0.11829838],
       [0.55413089, 0.33079593, 0.77888168, 0.11325551, 0.82448922],
       [0.26536104, 0.94429016, 0.0117463 , 0.35950454, 0.78628828]])

In [24]:
array_1==array_2

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [25]:
np.array_equal(array_1,array_2)

False

De uno de los arrays anteriores obten la media y muestra los valores que estan por encima de la media

In [26]:
media = array_1.mean()
media

np.float64(0.5117633347845633)

In [27]:
array_1[array_1>media]


array([0.87881346, 0.70915787, 0.99631287, 0.75517756, 0.68393273,
       0.6603961 , 0.82399602, 0.54326308, 0.53090704, 0.56175075,
       0.8767043 , 0.66638463, 0.71308245])

In [28]:
array_1

array([[0.25115134, 0.87881346, 0.35878896, 0.70915787, 0.28337425],
       [0.99631287, 0.0431614 , 0.75517756, 0.3201813 , 0.68393273],
       [0.6603961 , 0.45728438, 0.31255733, 0.39210108, 0.2065281 ],
       [0.82399602, 0.54326308, 0.53090704, 0.14128877, 0.56175075],
       [0.37244941, 0.25533817, 0.8767043 , 0.66638463, 0.71308245]])